# Copyright (c) 2000 - 2019 The Regents of the University of California.
# All rights reserved.	
# This includes the Generic yaml2rpm Makefile - most packaging should
# be able to use this.

ALL_TARGETS = default 
include $(YAML2RPM_HOME)/sys/Makefile

prep: 

default: prep
	make -f $(THISMAKE) $(PKGS) 

manifest: prep

