# This the Makefile for updated version group
ALL_TARGETS = versions_gcc6.yaml gcc6
include $(YAML2RPM_HOME)/sys/Makefile

# GCC6PKGS and GCC6TARGETS are defined in this included file
include Gcc6Defs.mk

GENEXTRAS = --map='{"versions.yaml":"versions_gcc6.yaml"}'

MANIFEST = $(GCC6PKGS)
VERSIONSFILE = versions_gcc6.yaml

versions: $(VERSIONSFILE)

$(VERSIONSFILE): versions.yaml versions.gcc6
	grep -v $$(cat versions.gcc6 | awk '{printf "-e ^%s ",$$1}') versions.yaml > $@
	cat versions.gcc6 >> $@

gcc6: versions 
	( for pkg in $(GCC6TARGETS); do 				\
		if [ -f $$pkg ]; then /bin/rm $$pkg; fi	;	\
                make -f $(THISMAKE) $$pkg; 			\
        done )
clean:
	- /bin/rm $(VERSIONSFILE) 
